spring.application.name=omnidex-backend

# Data Source
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Abilita l'inizializzazione SQL tramite Spring Boot
spring.sql.init.mode=always
spring.sql.init.separator=;